title: Welcome to my GitHub Pages
description: My Main GitHub Pages
show_downloads: true
google_analytics: [My Google Analytics tracking ID]
theme: jekyll-theme-cayman
plugins:
  - jekyll-toc
kramdown:
  parse_block_html: true
